2021-10-24 23:01:54,720 DEBUG    root            Loaded Command Group: ['gcloud', 'functions']
2021-10-24 23:01:54,851 DEBUG    root            Loaded Command Group: ['gcloud', 'functions', 'deploy']
2021-10-24 23:01:54,891 DEBUG    root            Running [gcloud.functions.deploy] with arguments: [--trigger-topic: "daily-bleeeeeefing-topic", NAME: "post_daily_bleeeeeefing"]
2021-10-24 23:01:54,963 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudfunctions.googleapis.com:443
2021-10-24 23:01:55,423 DEBUG    urllib3.connectionpool https://cloudfunctions.googleapis.com:443 "GET /v1/projects/bleeeeeefing/locations/us-central1/functions/post_daily_bleeeeeefing?alt=json HTTP/1.1" 404 None
2021-10-24 23:01:55,426 DEBUG    root            (gcloud.functions.deploy) Missing required argument [runtime]: Flag `--runtime` is required for new functions.
Traceback (most recent call last):
  File "/Users/katsuya2019/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/katsuya2019/Downloads/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 809, in Run
    resources = command_instance.Run(args)
  File "/Users/katsuya2019/Downloads/google-cloud-sdk/lib/surface/functions/deploy.py", line 83, in Run
    return command_v1.Run(args, track=self.ReleaseTrack())
  File "/Users/katsuya2019/Downloads/google-cloud-sdk/lib/googlecloudsdk/command_lib/functions/v1/deploy/command.py", line 335, in Run
    raise calliope_exceptions.RequiredArgumentException(
googlecloudsdk.calliope.exceptions.RequiredArgumentException: Missing required argument [runtime]: Flag `--runtime` is required for new functions.
2021-10-24 23:01:55,433 ERROR    root            (gcloud.functions.deploy) Missing required argument [runtime]: Flag `--runtime` is required for new functions.
2021-10-24 23:01:55,483 DEBUG    root            Metrics reporting process started...
